alias please="sudo"
alias gd="cd ~/My\ Drive"
alias mkp="cd $REPODIR/manuscript-object"
alias cs="cd $REPODIR"
alias csi="cd $REPODIR/columbiaspace.org"
alias activate="source .venv/bin/activate"
alias localhost="python3 -m http.server"
alias jpynb="~/.local/bin/jupyter-notebook --no-browser"
alias hindent="hindent --indent-size 2"
alias bc="bc -q"
alias loclat="~/.rbenv/shims/lolcat"
alias columbia="cd ~/My\ Drive/academics/columbia"
alias vg="valgrind --leak-check=yes"
alias pandocpdf="pandoc --pdf-engine=pdflatex.exe"
alias makeup="make -f ../Makefile"
alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"
alias pdf="zathura"
alias wrap="rlwrap"
alias ocamli="wrap ocaml"
alias sem="cd ~/My\ Drive/academics/columbia/sem4-sp22"
alias glowp="glow -p"
